import { gql } from '@apollo/client';

export const TOTAL_ITEMS = gql`
  query AllItemsInDatabase {
    allItemsInDatabase(limit: 1000) {
      totalCount
      data {
        askingPrice
        description
        id
        mainImageUrl
        title
        isDeleted
        categories
        imageUrls
        longitude,
        latitude,
      }
    }
  }
`;