import { gql } from '@apollo/client';

export const GET_ALL_USERS = gql`
  query getAllUsers {
    users(limit: 1000) {
      data {
        id
        firstName
        lastName
        email
        itemCount
        matchedItemCount
        gender
        avatarUrl
        isDeleted
      }
      totalCount
      hasNextPage
    }
  }
`;