import { gql } from '@apollo/client';

export const ITEM_ENGAGEMENTS = gql`
  query ItemEngagement {
    itemEngagement {
      dailyRegistrationTrend {
        count
        date
      }
      monthlyRegistrationTrend {
        count
        month
        year
      }
      weeklyRegistrationTrend {
        count
        week
        year
      }
    }
  }
`;