import { gql } from '@apollo/client';

export const GET_REPORTED_USERS = gql`
  query RestrictedUsers {
    restrictedUsers {
      id
      title
      description
      targetUser {
        id
        avatarUrl
        email
        firstName
        lastName
      }
      createdUser {
        avatarUrl
        email
        firstName
        lastName
      }
    }
  }
`;